export const STUDENTS = [
    "ABISHEK",
    "ADITHYAN",
    "ARAV",
    "ARJUN KRISHNA",
    "ASHIK",
    "DHRUPAD",
    "JISHNU C",
    "MUHAMMED",
    "SHAREEK",
    "NAVADEEPTH M",
    "NAVANEETH",
    "PRADHUL",
    "RANJITH",
    "SABARINATH",
    "SAMVRUTH",
    "SRAVAN SUNIL",
    "VISHNU P",
    "YADHU SADHAN",
    "ADHEENA K T",
    "AJANJALYA",
    "AMINA",
    "ANUDEVA",
    "ANUSREE",
    "NIVEDYA K",
    "SADHIKA",
    "AARJAV",
    "ABHIMANYU",
    "ADITYA MALAPPILAYI",
    "ADWAID RAJ",
    "AKSHAD",
    "ANUNAND",
    "ANURAG",
    "ANVIN",
    "ARPITH",
    "DHANUSH",
    "DHYAN",
    "ISHAN",
    "KARTHIK",
    "SAKETH",
    "SHAWN",
    "SREERENJ",
    "SREEVED",
    "SURYATHEJ",
    "SWARARAG",
    "YADUDEV KC",
    "AMAYA",
    "ARHITHA S",
    "NOURAH",
    "MAYOOGHA P",
    "MAYOOKHA K",
    "NIVEDYA PRIYAN",
    "POURNAMI",
    "ROSETTA",
    "SADAYA",
    "SHEHA",
    "FAIZ AL HANAN",
    "ZAYAN",
    "FIDAN",
    "HAYAN",
    "RIZAN",
    "RIZIN",
    "SHAZIN SUBAIR",
    "HAFILA"
].sort();
